### PR TITLE
Fixed Symfony 2.8 deprecation notices

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by XWB** [comment]
Ping @Gregwar :)

**Comment by XWB** [comment]
Ping @Gregwar

**Comment by Herod** [comment]
Off topic but until this is merged maybe people should look at this: https://gist.github.com/bjo3rnf/4061232

**Comment by XWB** [comment]
Ping @Gregwar

**Comment by Gregwar** [comment]
I guess this breaks Sf <2.8 bc, right?

**Comment by XWB** [comment]
@Gregwar It's backwards compatible, note I didn't remove the `getName()` method.

**Comment by Gregwar** [comment]
Yes, but is getParent returning a full class name correct with sf <2.8?

**Comment by XWB** [comment]
Good question. Ping @stof

**Comment by stof** [comment]
no it is not. It needs to return the form type name (same than when using the type). It is not hard to feature-detect what should be returned though

**Comment by XWB** [comment]
@Gregwar Fixed.

**Comment by Gregwar** [comment]
Ok, thanks for contributing

**Pull request merged**
